"""add tables

Revision ID: a082d32aa4c1
Revises: 
Create Date: 2026-03-16 09:40:15.353840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a082d32aa4c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('nombre_actividad', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_index(op.f('ix_actividades_id_actividad'), 'actividades', ['id_actividad'], unique=False)
    op.create_table('emociones',
    sa.Column('id_emocion', sa.Integer(), nullable=False),
    sa.Column('nombre_emocion', sa.String(length=50), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_emocion')
    )
    op.create_index(op.f('ix_emociones_id_emocion'), 'emociones', ['id_emocion'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('foto_perfil', sa.Text(), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.Column('carrera', sa.String(length=150), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('estadisticas',
    sa.Column('id_estadistica', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('emocion_predominante', sa.String(length=50), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('porcentaje_increible', sa.Float(), nullable=True),
    sa.Column('porcentaje_bien', sa.Float(), nullable=True),
    sa.Column('porcentaje_meh', sa.Float(), nullable=True),
    sa.Column('porcentaje_mal', sa.Float(), nullable=True),
    sa.Column('porcentaje_horrible', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_estadistica')
    )
    op.create_index(op.f('ix_estadisticas_id_estadistica'), 'estadisticas', ['id_estadistica'], unique=False)
    op.create_table('registros_emocionales',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_emocion', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_emocion'], ['emociones.id_emocion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_index(op.f('ix_registros_emocionales_id_registro'), 'registros_emocionales', ['id_registro'], unique=False)
    op.create_table('chats',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_registro'], ['registros_emocionales.id_registro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_index(op.f('ix_chats_id_chat'), 'chats', ['id_chat'], unique=False)
    op.create_table('registro_actividad',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividades.id_actividad'], ),
    sa.ForeignKeyConstraint(['id_registro'], ['registros_emocionales.id_registro'], ),
    sa.PrimaryKeyConstraint('id_registro', 'id_actividad')
    )
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=True),
    sa.Column('emisor', sa.Enum('usuario', 'IA', name='tipoemisor'), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chats.id_chat'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_index(op.f('ix_mensajes_id_mensaje'), 'mensajes', ['id_mensaje'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_id_mensaje'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_table('registro_actividad')
    op.drop_index(op.f('ix_chats_id_chat'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_registros_emocionales_id_registro'), table_name='registros_emocionales')
    op.drop_table('registros_emocionales')
    op.drop_index(op.f('ix_estadisticas_id_estadistica'), table_name='estadisticas')
    op.drop_table('estadisticas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_emociones_id_emocion'), table_name='emociones')
    op.drop_table('emociones')
    op.drop_index(op.f('ix_actividades_id_actividad'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###
